server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://217.60.249.94:3306/personal_cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: personal
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.cloudspace.entity

auth:
  whitelist:
    - /error
    - /space/create

user:
  auth: http://45.154.2.158:8081